postgres:
  image: postgres:9.4.5
  environment:
    POSTGRES_USER: rorondocker
    POSTGRES_PASSWORD: kaunsapassword
  ports:
    - '5432:5432'
  volumes:
    - rorondocker-postgres:/var/lib/postgresql/data

redis:
  image: redis:3.0.5
  ports:
    - '6379:6379'
  volumes:
    - rorondocker-redis:/var/lib/redis/data

rorondocker:
  build: .
  links:
    - postgres
    - redis
  volumes:
    - .:/rorondocker
  ports:
    - '8000:8000'
  env_file:
    - .rorondocker.env

sidekiq:
  build: .
  command: bundle exec sidekiq -C config/sidekiq.yml
  links:
    - postgres
    - redis
  volumes:
    - .:/rorondocker
  env_file:
    - .rorondocker.env